### ISSUE TITLE
Issues for start running the MetaPro

### ISSUE THREAD

**Issue by yeolex** [ParkinsonLab/MetaPro#32]
We have some problems to run the pipeline:

1. In the intructions you say 

docker run python3 /pipeline/MetaPro.py -c <your config.ini> -1 <your forward read.fastq> -2 <your reverse read.fastq> -o <your output directory>

Is docker run python3 /pipeline/MetaPro.py a command to run MetaPro.py inside a Docker container? If so, should we pull an image and then run the command with -it -v to create a local path within the Docker container? Is the image parkinsonlab/metapro:v3.0.1?

2. In the config.ini file, should the paths to the databases be specified as local paths or container paths? For example:

docker run -it -v /local/path:/container/path parkinsonlab/metapro:v3.0.1 
python3 /pipeline/MetaPro.py -c /container/path/config.ini -1 /container/path/forward_read.fastq -2 /container/path/reverse_read.fastq -o /container/path/output_directory

Please don't close this issue yet, as we have more questions to address.

Thanks, and I appreciate your time

**Comment by billylaw8** [comment]
0) each ticket corresponds to each issue.  If the issue is related, then feel free to reopen.  Otherwise, please issue a new ticket if the context changes.  We're trying to keep track of user experiences.  It goes to inform us of next directions. Thanks

Also: this question you're asking aren't issues with MetaPro, but with how to use Docker in general.  Please see their documentation for further insight. 
https://docs.docker.com/get-started/introduction/

1) The pipeline is python code, housed inside the docker container., and run inside the docker image.  Docker is a software container, similar to virtualboxes <but the tech underneath is different>.

2) your config file problems are related to your bind-mounting <a fundamental feature in docker that lets the container access paths within your setup/host machine/PC>  This isn't something that we can code for everyone, and is 100% a Docker user issue.  Not a MetaPro issue.

**Comment by yeolex** [comment]
Thanks for your answer.

Is the image parkinsonlab/metapro:v3.0.1?

We are working on the entire introduction to Docker and will comment to you as soon as possible.
